//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(Frog)

const palette_color_t Frog_palettes[4] = {
	RGB8(188,213,140), RGB8(134,173, 63), RGB8( 67, 86, 32), RGB8(  0,  0,  0)
	
};

const uint8_t Frog_tiles[32] = {
	0x78,0x78,0xb7,0xcf,
	0xff,0xb4,0xb7,0xcc,
	0x78,0x7f,0xbf,0xc0,
	0xff,0xbf,0xbf,0xc0,
	
0x7f,0x7f,0x40,0x7f,
	0x80,0xff,0xee,0x9b,
	0x6e,0x5b,0xcf,0xbb,
	0xfa,0xf6,0x1c,0x1c
	
};

const metasprite_t Frog_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_ITEM(8, -8, 1, S_PAL(0)),
	METASPR_ITEM(0, 8, 1, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const Frog_metasprites[1] = {
	Frog_metasprite0
};
