//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Frog_H
#define METASPRITE_Frog_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Frog_TILE_ORIGIN 0
#define Frog_TILE_W 8
#define Frog_TILE_H 8
#define Frog_WIDTH 16
#define Frog_HEIGHT 16
#define Frog_TILE_COUNT 2
#define Frog_PALETTE_COUNT 1
#define Frog_COLORS_PER_PALETTE 4
#define Frog_TOTAL_COLORS 4
#define Frog_PIVOT_X 8
#define Frog_PIVOT_Y 8
#define Frog_PIVOT_W 16
#define Frog_PIVOT_H 16
extern const metasprite_t* const Frog_metasprites[1];

BANKREF_EXTERN(Frog)

extern const palette_color_t Frog_palettes[4];
extern const uint8_t Frog_tiles[32];

#endif
