//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_StartbucksSplash_H
#define METASPRITE_StartbucksSplash_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define StartbucksSplash_TILE_ORIGIN 0
#define StartbucksSplash_TILE_W 8
#define StartbucksSplash_TILE_H 8
#define StartbucksSplash_WIDTH 160
#define StartbucksSplash_HEIGHT 144
#define StartbucksSplash_TILE_COUNT 245
#define StartbucksSplash_PALETTE_COUNT 1
#define StartbucksSplash_COLORS_PER_PALETTE 4
#define StartbucksSplash_TOTAL_COLORS 4
#define StartbucksSplash_MAP_ATTRIBUTES 0
extern const unsigned char StartbucksSplash_map[360];
#define StartbucksSplash_map_attributes StartbucksSplash_map

BANKREF_EXTERN(StartbucksSplash)

extern const palette_color_t StartbucksSplash_palettes[4];
extern const uint8_t StartbucksSplash_tiles[3920];

#endif
